[package]
name = "kyushu"
description = "kyushu is a journaling application which let you deliberate on events and your journey through them"
version = "0.1.4"
edition = "2021"
authors = ["Amir Alesheikh <amirhossein.alehseikh@gmail.com>"]

homepage = "https://github.com/amirography/soapberry/tree/main/crates/kyushu"
repository = "https://github.com/amirography/soapberry/tree/main/crates/kyushu"
license = "Apache-2.0"
readme = "README.md"
categories = ["command-line-utilities"]
keywords = ["journaling", "events"]

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/server.rs"
name = "kyushu-server"

[[bin]]
path = "src/client.rs"
name = "kyushu-client"


[dependencies]
prost = "0.11.8"
tokio = { version = "1.26.0", features = ["rt", "macros", "rt-multi-thread"] }
tonic = "0.8.3"


[build-dependencies]
tonic-build = "0.8.4"
